/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

// Dylan Denny TP074879

// TO WHOEVER ACCESS MY SOURCE CODE, BY READING THIS YOU AGREE TO NOT STEAL ANY OF MY SOURCE CODE.
// I HAVE GO THROUGH MY WAYS AND STAY UP 4AM JUST TO UNDERSTAND HOW JAVA PROGRAMMING WORKS, PLEASE DON'T QUESTION MY SANITY.
// HONESTLY WHOEVER READS MY CODE ENJOY HAVING BUNCH OF COMMENTS BECAUSE THIS IS HOW I CODE.
// BEST OF LUCK TO ALL MY FRIENDS THIS SEMESTER.
// CODE MAY BE REDUNDANT AND NOT FLEXIBLE FOR OTHER TEAMMATE CODE, HOWEVER MY CODE IS PROBABLY ONLY FLEXIBLE WITHIN MY RANGE.

// For Error Handler -=-=-=-=-=-=-=-=-=-
import java.io.FileNotFoundException;
import java.io.IOException;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// For UI output -=-=-=-=-=-=-=-=-=-=-=-
import javax.swing.JOptionPane;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// For Window Closing -=-=-=-=-=-=-=-=-=
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

public class Login extends javax.swing.JFrame {
    
    // Global Variables : FailedAttempts
    
    private int FailedAttempts = 0;
    
    /**
     * Creates new form Login
     */
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }
    
    // JFrame Swing Close Methods - Reference : https://youtu.be/hFv2Uay0qj0?si=x8NB78V7pPxs39it&t=133
    
    public void WindowClose(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel_MainFrame = new javax.swing.JPanel();
        LabelDisplay_Login = new javax.swing.JLabel();
        LabelDisplay_Name = new javax.swing.JLabel();
        LabelDisplay_Password = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        TxtName = new javax.swing.JTextField();
        TxtPW = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        Panel_MainFrame.setBackground(new java.awt.Color(51, 51, 51));

        LabelDisplay_Login.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelDisplay_Login.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Login.setText("LOGIN");

        LabelDisplay_Name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_Name.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Name.setText("Name :");

        LabelDisplay_Password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_Password.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Password.setText("Password :");

        LoginButton.setBackground(new java.awt.Color(30, 30, 30));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        TxtName.setBackground(new java.awt.Color(30, 30, 30));
        TxtName.setForeground(new java.awt.Color(255, 255, 255));
        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        TxtPW.setBackground(new java.awt.Color(30, 30, 30));
        TxtPW.setForeground(new java.awt.Color(255, 255, 255));
        TxtPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_MainFrameLayout = new javax.swing.GroupLayout(Panel_MainFrame);
        Panel_MainFrame.setLayout(Panel_MainFrameLayout);
        Panel_MainFrameLayout.setHorizontalGroup(
            Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(LabelDisplay_Login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_MainFrameLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_MainFrameLayout.createSequentialGroup()
                        .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDisplay_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtPW, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                                    .addComponent(LabelDisplay_Name)
                                    .addGap(227, 227, 227))
                                .addComponent(TxtName)))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_MainFrameLayout.createSequentialGroup()
                        .addComponent(LoginButton)
                        .addGap(139, 139, 139))))
        );
        Panel_MainFrameLayout.setVerticalGroup(
            Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(LabelDisplay_Login)
                .addGap(77, 77, 77)
                .addComponent(LabelDisplay_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelDisplay_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(LoginButton)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("INVENTORY MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(Panel_MainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_MainFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(235, 235, 235))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

        String Name = TxtName.getText();
        char[] HasedPassword = TxtPW.getPassword();
        String Password = new String(HasedPassword);
        // Although char is not really needed, 
        // I've did some research and people said using this technique makes the security better
        // in real life statements so might as well do it lol.
        
        try {
            // LoginVerification Method -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
            if (LoginMethods.LoginVerification(Name, Password)) {
                JOptionPane.showMessageDialog(rootPane, "Login successful, you will be directed shortly...");
                FailedAttempts = 0; // Reset to 0 if login successful.
                WindowClose();
                HomePage WindowFrame = new HomePage();
                WindowFrame.setVisible(true);
                // MORE CODE
                // I am going to leave this comment so I can code
            } else {
                FailedAttempts++;
                if (FailedAttempts >= 3){
                    JOptionPane.showMessageDialog(rootPane, "Too many attempts, closing...", "Too Much!", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid username or password.", "Failed!", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, "Error: File not found, perhaps try to double check the file?");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error: Unable to register user due to Input/Output issue.");
        } finally {
            TxtName.setText("");
            TxtPW.setText("");
            // I used Try Catch before Lecturer's teaching schedule, so there's that. I got it from:
            // https://www.w3schools.com/java/java_try_catch.asp
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameActionPerformed

    private void TxtPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDisplay_Login;
    private javax.swing.JLabel LabelDisplay_Name;
    private javax.swing.JLabel LabelDisplay_Password;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel Panel_MainFrame;
    private javax.swing.JTextField TxtName;
    private javax.swing.JPasswordField TxtPW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
