/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

// Dylan Denny TP074879

// TO WHOEVER ACCESS MY SOURCE CODE, BY READING THIS YOU AGREE TO NOT STEAL ANY OF MY SOURCE CODE.
// I HAVE GO THROUGH MY WAYS AND STAY UP 4AM JUST TO UNDERSTAND HOW JAVA PROGRAMMING WORKS, PLEASE DON'T QUESTION MY SANITY.
// HONESTLY WHOEVER READS MY CODE ENJOY HAVING BUNCH OF COMMENTS BECAUSE THIS IS HOW I CODE.
// BEST OF LUCK TO ALL MY FRIENDS THIS SEMESTER.
// CODE MAY BE REDUNDANT AND NOT FLEXIBLE FOR OTHER TEAMMATE CODE, HOWEVER MY CODE IS PROBABLY ONLY FLEXIBLE WITHIN MY RANGE.

// For UI Output -=-=-=-=-=-=-=-=-=-=-=-
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// For DateRegister -=-=-=-=-=-=-=-=-=-=
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// Table -=-=-=-=-=-=-=
import javax.swing.table.DefaultTableModel;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

public class ItemCreation extends javax.swing.JFrame {

    /**
     * Creates new form Item_Creation
     */
    // JFrame Swing Close Methods - Reference : https://youtu.be/hFv2Uay0qj0?si=x8NB78V7pPxs39it&t=133
    public void WindowClose() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    private DefaultTableModel SupplierTableModel;
    private DefaultTableModel PPETableModel;

    public ItemCreation() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);

        SupplierTableModel = (DefaultTableModel) SupplierTxtTable.getModel();
        PPETableModel = (DefaultTableModel) PPETxtTable.getModel();

        try {
            ItemCreationMethods.LoadSuppliers_WILDCARD(SupplierTableModel);
            ItemCreationMethods.LoadPPE(PPETableModel);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemName_Group = new javax.swing.ButtonGroup();
        Panel_MainFrame = new javax.swing.JPanel();
        LabelDisplay_ItemCreation = new javax.swing.JLabel();
        ItemCreateButton = new javax.swing.JButton();
        Panel_ItemName = new javax.swing.JPanel();
        HeadCover_Option = new javax.swing.JRadioButton();
        FaceShield_Option = new javax.swing.JRadioButton();
        Mask_Option = new javax.swing.JRadioButton();
        Gloves_Option = new javax.swing.JRadioButton();
        Gown_Option = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        LabelDisplay_ItemName = new javax.swing.JLabel();
        LabelDisplay_SupplierTable = new javax.swing.JLabel();
        SupplierCode_TextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SupplierTxtTable = new javax.swing.JTable();
        LabelDisplay_SupplierCode1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PPETxtTable = new javax.swing.JTable();
        LabelDisplay_ItemTable = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        SupplierCreate = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel_MainFrame.setBackground(new java.awt.Color(40, 40, 40));

        LabelDisplay_ItemCreation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelDisplay_ItemCreation.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_ItemCreation.setText("ITEM CREATION");

        ItemCreateButton.setBackground(new java.awt.Color(30, 30, 30));
        ItemCreateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ItemCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        ItemCreateButton.setText("Create");
        ItemCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ItemCreateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ItemCreateButtonMouseExited(evt);
            }
        });
        ItemCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCreateButtonActionPerformed(evt);
            }
        });

        Panel_ItemName.setBackground(new java.awt.Color(20, 20, 20));
        Panel_ItemName.setForeground(new java.awt.Color(255, 255, 255));

        ItemName_Group.add(HeadCover_Option);
        HeadCover_Option.setForeground(new java.awt.Color(255, 255, 255));
        HeadCover_Option.setText("Head Cover");
        HeadCover_Option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeadCover_OptionActionPerformed(evt);
            }
        });

        ItemName_Group.add(FaceShield_Option);
        FaceShield_Option.setForeground(new java.awt.Color(255, 255, 255));
        FaceShield_Option.setText("Face Shield");

        ItemName_Group.add(Mask_Option);
        Mask_Option.setForeground(new java.awt.Color(255, 255, 255));
        Mask_Option.setText("Mask");
        Mask_Option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mask_OptionActionPerformed(evt);
            }
        });

        ItemName_Group.add(Gloves_Option);
        Gloves_Option.setForeground(new java.awt.Color(255, 255, 255));
        Gloves_Option.setText("Gloves");
        Gloves_Option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gloves_OptionActionPerformed(evt);
            }
        });

        ItemName_Group.add(Gown_Option);
        Gown_Option.setForeground(new java.awt.Color(255, 255, 255));
        Gown_Option.setText("Gown");

        ItemName_Group.add(jRadioButton6);
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Shoe Covers");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_ItemNameLayout = new javax.swing.GroupLayout(Panel_ItemName);
        Panel_ItemName.setLayout(Panel_ItemNameLayout);
        Panel_ItemNameLayout.setHorizontalGroup(
            Panel_ItemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ItemNameLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(Panel_ItemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_ItemNameLayout.createSequentialGroup()
                        .addComponent(HeadCover_Option, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(Mask_Option, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_ItemNameLayout.createSequentialGroup()
                        .addComponent(FaceShield_Option, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Gloves_Option, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112)
                .addGroup(Panel_ItemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Gown_Option, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );
        Panel_ItemNameLayout.setVerticalGroup(
            Panel_ItemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ItemNameLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Panel_ItemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeadCover_Option)
                    .addComponent(Mask_Option)
                    .addComponent(Gown_Option))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_ItemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FaceShield_Option)
                    .addComponent(Gloves_Option)
                    .addComponent(jRadioButton6))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        LabelDisplay_ItemName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_ItemName.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_ItemName.setText("Item Name:");

        LabelDisplay_SupplierTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_SupplierTable.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_SupplierTable.setText("Suppliers Table");

        SupplierCode_TextField.setBackground(new java.awt.Color(30, 30, 30));
        SupplierCode_TextField.setForeground(new java.awt.Color(255, 255, 255));
        SupplierCode_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierCode_TextFieldActionPerformed(evt);
            }
        });

        SupplierTxtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Supplier Code", "Supplier Name", "Register Date"
            }
        ));
        SupplierTxtTable.setSelectionBackground(new java.awt.Color(40, 40, 40));
        jScrollPane1.setViewportView(SupplierTxtTable);

        LabelDisplay_SupplierCode1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_SupplierCode1.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_SupplierCode1.setText("Supplier Code:");

        PPETxtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Supplier Code", "Date Added"
            }
        ));
        PPETxtTable.setSelectionBackground(new java.awt.Color(40, 40, 40));
        jScrollPane2.setViewportView(PPETxtTable);

        LabelDisplay_ItemTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_ItemTable.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_ItemTable.setText("Item Table");

        BackButton.setBackground(new java.awt.Color(30, 30, 30));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        SupplierCreate.setBackground(new java.awt.Color(30, 30, 30));
        SupplierCreate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SupplierCreate.setForeground(new java.awt.Color(255, 255, 255));
        SupplierCreate.setText("Create");
        SupplierCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupplierCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupplierCreateMouseExited(evt);
            }
        });
        SupplierCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierCreateActionPerformed(evt);
            }
        });

        RefreshButton.setBackground(new java.awt.Color(30, 30, 30));
        RefreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RefreshButton.setForeground(new java.awt.Color(255, 255, 255));
        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_MainFrameLayout = new javax.swing.GroupLayout(Panel_MainFrame);
        Panel_MainFrame.setLayout(Panel_MainFrameLayout);
        Panel_MainFrameLayout.setHorizontalGroup(
            Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(LabelDisplay_ItemCreation))
                    .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDisplay_SupplierCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                                    .addComponent(SupplierCode_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RefreshButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(BackButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ItemCreateButton))
                                .addComponent(Panel_ItemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelDisplay_ItemName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_MainFrameLayout.createSequentialGroup()
                                    .addComponent(LabelDisplay_SupplierTable, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SupplierCreate))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(LabelDisplay_ItemTable, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        Panel_MainFrameLayout.setVerticalGroup(
            Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDisplay_ItemCreation)
                .addGap(55, 55, 55)
                .addComponent(LabelDisplay_ItemName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(LabelDisplay_SupplierCode1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemCreateButton)
                    .addComponent(SupplierCode_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton)
                    .addComponent(RefreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(LabelDisplay_ItemTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelDisplay_SupplierTable))
                    .addComponent(SupplierCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemCreateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemCreateButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemCreateButtonMouseEntered

    private void ItemCreateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemCreateButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemCreateButtonMouseExited

    private void ItemCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCreateButtonActionPerformed
        String ItemCode = "";
        String ItemName = "";
        String Quantity = "100";
        String SupplierCode = SupplierCode_TextField.getText();

        DateTimeFormatter DateRegisterFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String DateAdded = LocalDate.now().format(DateRegisterFormat);

        // I got too lazy and I know people are too lazy to type, so I do JButton instead.
        // Thank you to the past me!
        if (HeadCover_Option.isSelected()) {
            ItemCode = "HC";
            ItemName = "Head Cover";
        } else if (FaceShield_Option.isSelected()) {
            ItemCode = "FS";
            ItemName = "Face Shield";
        } else if (Mask_Option.isSelected()) {
            ItemCode = "MS";
            ItemName = "Mask";
        } else if (Gloves_Option.isSelected()) {
            ItemCode = "GL";
            ItemName = "Gloves";
        } else if (Gown_Option.isSelected()) {
            ItemCode = "GW";
            ItemName = "Gown";
        } else if (jRadioButton6.isSelected()) {
            ItemCode = "SC";
            ItemName = "Shoe Covers";
        } else {
            JOptionPane.showMessageDialog(this, "Please select an item.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            if (ItemCreationMethods.ItemExist(ItemCode)) {
                JOptionPane.showMessageDialog(this, "Item already exists.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!ItemCreationMethods.SupplierExists_WILDCARD(SupplierCode)) {
                JOptionPane.showMessageDialog(this, "Supplier code does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error checking item existence.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return;
        }

        if (SupplierCode.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Supplier Code cannot be Empty.", "Supplier code missing", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // New PPE Object -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
        PPE_Encapsulation NewItem = new PPE_Encapsulation(ItemCode, ItemName, Quantity, SupplierCode, DateAdded);
        // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

        try {
            ItemCreationMethods.FileWrite(NewItem);
            JOptionPane.showMessageDialog(rootPane, "Item successfully created.", "Wahoo!", JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, "Error: File not found, perhaps try to double check the file?");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error: Unable to create Item due to Input/Output issue.");
        }
    }//GEN-LAST:event_ItemCreateButtonActionPerformed

    private void HeadCover_OptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeadCover_OptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeadCover_OptionActionPerformed

    private void Mask_OptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mask_OptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mask_OptionActionPerformed

    private void Gloves_OptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gloves_OptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gloves_OptionActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void SupplierCode_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierCode_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierCode_TextFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SupplierCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierCreateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierCreateMouseEntered

    private void SupplierCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierCreateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierCreateMouseExited

    private void SupplierCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierCreateActionPerformed
        try {
            if (SupplierCreationMethod.CheckSupplierLimit()) {
                JOptionPane.showMessageDialog(this, "Maximum of 3 suppliers already registered. Cannot register more suppliers.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                SupplierCreation WindowFrame = new SupplierCreation();
                WindowFrame.setVisible(true);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SupplierCreateActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        try {
            ItemCreationMethods.LoadSuppliers_WILDCARD(SupplierTableModel);
            ItemCreationMethods.LoadPPE(PPETableModel);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_RefreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemCreation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton FaceShield_Option;
    private javax.swing.JRadioButton Gloves_Option;
    private javax.swing.JRadioButton Gown_Option;
    private javax.swing.JRadioButton HeadCover_Option;
    private javax.swing.JButton ItemCreateButton;
    private javax.swing.ButtonGroup ItemName_Group;
    private javax.swing.JLabel LabelDisplay_ItemCreation;
    private javax.swing.JLabel LabelDisplay_ItemName;
    private javax.swing.JLabel LabelDisplay_ItemTable;
    private javax.swing.JLabel LabelDisplay_SupplierCode1;
    private javax.swing.JLabel LabelDisplay_SupplierTable;
    private javax.swing.JRadioButton Mask_Option;
    private javax.swing.JTable PPETxtTable;
    private javax.swing.JPanel Panel_ItemName;
    private javax.swing.JPanel Panel_MainFrame;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JTextField SupplierCode_TextField;
    private javax.swing.JButton SupplierCreate;
    private javax.swing.JTable SupplierTxtTable;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
