/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

// Dylan Denny TP074879

// TO WHOEVER ACCESS MY SOURCE CODE, BY READING THIS YOU AGREE TO NOT STEAL ANY OF MY SOURCE CODE.
// I HAVE GO THROUGH MY WAYS AND STAY UP 4AM JUST TO UNDERSTAND HOW JAVA PROGRAMMING WORKS, PLEASE DON'T QUESTION MY SANITY.
// HONESTLY WHOEVER READS MY CODE ENJOY HAVING BUNCH OF COMMENTS BECAUSE THIS IS HOW I CODE.
// BEST OF LUCK TO ALL MY FRIENDS THIS SEMESTER.
// CODE MAY BE REDUNDANT AND NOT FLEXIBLE FOR OTHER TEAMMATE CODE, HOWEVER MY CODE IS PROBABLY ONLY FLEXIBLE WITHIN MY RANGE.


// For Error Handler -=-=-=-=-=-=-=-=-=-
import java.io.FileNotFoundException;
import java.io.IOException;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// For UI output -=-=-=-=-=-=-=-=-=-=-=-
import javax.swing.JOptionPane;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

public class Modify extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    
    public Modify() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }
    
    private String userID;
    private String currentName;
    private String currentPassword;
    private String currentUserType;
    
    public Modify(String userID, String currentName, String currentPassword, String currentUserType) {
        this.userID = userID;
        this.currentName = currentName;
        this.currentPassword = currentPassword;
        this.currentUserType = currentUserType;

        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);

        // Set the text fields with the current user information
        ModifyName.setText(currentName);
        ModifyPassword.setText(currentPassword);
        if (currentUserType.equals("Admin")) {
            ModifyUserAdmin.setSelected(true);
        } else if (currentUserType.equals("Staff")) {
            ModifyUserStaff.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_Staff_Option = new javax.swing.ButtonGroup();
        Panel_MainFrame = new javax.swing.JPanel();
        LabelDisplay_Modify = new javax.swing.JLabel();
        LabelDisplay_Name = new javax.swing.JLabel();
        LabelDisplay_Password = new javax.swing.JLabel();
        ModifyButton = new javax.swing.JButton();
        ModifyName = new javax.swing.JTextField();
        ModifyPassword = new javax.swing.JTextField();
        LabelDisplay_UserType = new javax.swing.JLabel();
        ModifyUserAdmin = new javax.swing.JRadioButton();
        ModifyUserStaff = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel_MainFrame.setBackground(new java.awt.Color(51, 51, 51));

        LabelDisplay_Modify.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelDisplay_Modify.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Modify.setText("MODIFY");

        LabelDisplay_Name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_Name.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Name.setText("Name :");

        LabelDisplay_Password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_Password.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Password.setText("Password :");

        ModifyButton.setBackground(new java.awt.Color(30, 30, 30));
        ModifyButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ModifyButton.setForeground(new java.awt.Color(255, 255, 255));
        ModifyButton.setText("Modify");
        ModifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModifyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModifyButtonMouseExited(evt);
            }
        });
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });

        ModifyName.setBackground(new java.awt.Color(30, 30, 30));
        ModifyName.setForeground(new java.awt.Color(255, 255, 255));
        ModifyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyNameActionPerformed(evt);
            }
        });

        ModifyPassword.setBackground(new java.awt.Color(30, 30, 30));
        ModifyPassword.setForeground(new java.awt.Color(255, 255, 255));
        ModifyPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyPasswordActionPerformed(evt);
            }
        });

        LabelDisplay_UserType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_UserType.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_UserType.setText("User Type :");

        Admin_Staff_Option.add(ModifyUserAdmin);
        ModifyUserAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ModifyUserAdmin.setForeground(new java.awt.Color(255, 255, 255));
        ModifyUserAdmin.setText("Admin");

        Admin_Staff_Option.add(ModifyUserStaff);
        ModifyUserStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ModifyUserStaff.setForeground(new java.awt.Color(255, 255, 255));
        ModifyUserStaff.setText("Staff");

        javax.swing.GroupLayout Panel_MainFrameLayout = new javax.swing.GroupLayout(Panel_MainFrame);
        Panel_MainFrame.setLayout(Panel_MainFrameLayout);
        Panel_MainFrameLayout.setHorizontalGroup(
            Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_MainFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ModifyButton)
                .addGap(157, 157, 157))
            .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelDisplay_Name)
                    .addComponent(LabelDisplay_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDisplay_UserType, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModifyUserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDisplay_Modify)
                    .addComponent(ModifyName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifyUserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        Panel_MainFrameLayout.setVerticalGroup(
            Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDisplay_Modify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDisplay_Name)
                    .addComponent(ModifyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDisplay_Password))
                .addGap(27, 27, 27)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDisplay_UserType)
                    .addComponent(ModifyUserAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModifyUserStaff)
                .addGap(39, 39, 39)
                .addComponent(ModifyButton)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        
        String Name = ModifyName.getText();
        String Password = ModifyPassword.getText();
        String UserID = this.userID;
        String UserType = "";
        
        if (ModifyUserAdmin.isSelected()) {
            UserType = "Admin";
        } else if (ModifyUserStaff.isSelected()) {
            UserType = "Staff";
        } else {
            UserType = "";
        }    
        
        String ValidationErrors = RegisterMethods.EmptyInputValidation(Name, Password, ModifyUserAdmin.isSelected(), ModifyUserStaff.isSelected());
    
        if (!ValidationErrors.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, ValidationErrors);
            return;
        }
        
        try {
            // DuplicateNameCheck Method -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            boolean NameChangedCheck = !Name.equals(this.currentName); // Use the current name instead of userID

            if (NameChangedCheck) {
                if (RegisterMethods.DuplicateNameCheck(Name)) {
                    JOptionPane.showMessageDialog(rootPane, "Error: The name " + Name + " is already registered.", "Duplicate Name", JOptionPane.ERROR_MESSAGE);
                    return;
                }
        }
            // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            
            // Update the User -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            UserManagementMethods.ModifyUser(UserID, Name, Password, UserType);
            JOptionPane.showMessageDialog(rootPane, "User successfully modified. Please refresh to see the latest version.", "Wahoo!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, "Error: File not found, perhaps try to double check the file?");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error: Unable to register user due to Input/Output issue.");
        }
    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void ModifyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyNameActionPerformed

    private void ModifyPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyPasswordActionPerformed

    private void ModifyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyButtonMouseEntered

    private void ModifyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Admin_Staff_Option;
    private javax.swing.JLabel LabelDisplay_Modify;
    private javax.swing.JLabel LabelDisplay_Name;
    private javax.swing.JLabel LabelDisplay_Password;
    private javax.swing.JLabel LabelDisplay_UserType;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JTextField ModifyName;
    private javax.swing.JTextField ModifyPassword;
    private javax.swing.JRadioButton ModifyUserAdmin;
    private javax.swing.JRadioButton ModifyUserStaff;
    private javax.swing.JPanel Panel_MainFrame;
    // End of variables declaration//GEN-END:variables
}
