/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

// Dylan Denny TP074879

// TO WHOEVER ACCESS MY SOURCE CODE, BY READING THIS YOU AGREE TO NOT STEAL ANY OF MY SOURCE CODE.
// I HAVE GO THROUGH MY WAYS AND STAY UP 4AM JUST TO UNDERSTAND HOW JAVA PROGRAMMING WORKS, PLEASE DON'T QUESTION MY SANITY.
// HONESTLY WHOEVER READS MY CODE ENJOY HAVING BUNCH OF COMMENTS BECAUSE THIS IS HOW I CODE.
// BEST OF LUCK TO ALL MY FRIENDS THIS SEMESTER.
// CODE MAY BE REDUNDANT AND NOT FLEXIBLE FOR OTHER TEAMMATE CODE, HOWEVER MY CODE IS PROBABLY ONLY FLEXIBLE WITHIN MY RANGE.

// For Error Handler -=-=-=-=-=-=-=-=-=-
import java.io.FileNotFoundException;
import java.io.IOException;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// For UI output -=-=-=-=-=-=-=-=-=-=-=-
import javax.swing.JOptionPane;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// For DateRegister -=-=-=-=-=-=-=-=-=-=
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_Staff_Option = new javax.swing.ButtonGroup();
        Panel_MainFrame = new javax.swing.JPanel();
        LabelDisplay_Register = new javax.swing.JLabel();
        LabelDisplay_Name = new javax.swing.JLabel();
        LabelDisplay_Password = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        TxtName = new javax.swing.JTextField();
        TxtPW = new javax.swing.JTextField();
        LabelDisplay_UserType = new javax.swing.JLabel();
        UserAdmin = new javax.swing.JRadioButton();
        UserStaff = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel_MainFrame.setBackground(new java.awt.Color(51, 51, 51));

        LabelDisplay_Register.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelDisplay_Register.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Register.setText("REGISTER");

        LabelDisplay_Name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_Name.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Name.setText("Name :");

        LabelDisplay_Password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_Password.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Password.setText("Password :");

        RegisterButton.setBackground(new java.awt.Color(30, 30, 30));
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseExited(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        TxtName.setBackground(new java.awt.Color(30, 30, 30));
        TxtName.setForeground(new java.awt.Color(255, 255, 255));
        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        TxtPW.setBackground(new java.awt.Color(30, 30, 30));
        TxtPW.setForeground(new java.awt.Color(255, 255, 255));
        TxtPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPWActionPerformed(evt);
            }
        });

        LabelDisplay_UserType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_UserType.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_UserType.setText("User Type :");

        Admin_Staff_Option.add(UserAdmin);
        UserAdmin.setForeground(new java.awt.Color(255, 255, 255));
        UserAdmin.setText("Admin");

        Admin_Staff_Option.add(UserStaff);
        UserStaff.setForeground(new java.awt.Color(255, 255, 255));
        UserStaff.setText("Staff");

        javax.swing.GroupLayout Panel_MainFrameLayout = new javax.swing.GroupLayout(Panel_MainFrame);
        Panel_MainFrame.setLayout(Panel_MainFrameLayout);
        Panel_MainFrameLayout.setHorizontalGroup(
            Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_MainFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterButton)
                .addGap(157, 157, 157))
            .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelDisplay_Name)
                    .addComponent(LabelDisplay_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDisplay_UserType, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDisplay_Register)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPW, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        Panel_MainFrameLayout.setVerticalGroup(
            Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDisplay_Register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDisplay_Name)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDisplay_Password))
                .addGap(27, 27, 27)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDisplay_UserType)
                    .addComponent(UserAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserStaff)
                .addGap(39, 39, 39)
                .addComponent(RegisterButton)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        
        String Name = TxtName.getText();
        String Password = TxtPW.getText();
        String UserID = "";
        String UserType = "";
        
        DateTimeFormatter DateRegisterFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String DateRegister = LocalDate.now().format(DateRegisterFormat);
        
        if (UserAdmin.isSelected()) {
            UserType = "Admin";
        } else if (UserStaff.isSelected()) {
            UserType = "Staff";
        } else {
            UserType = "";
        }    
        
        String ValidationErrors = RegisterMethods.EmptyInputValidation(Name, Password, UserAdmin.isSelected(), UserStaff.isSelected());
    
        if (!ValidationErrors.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, ValidationErrors);
            return;
        }
        
        try {
            // DuplicateNameCheck Method -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            if (RegisterMethods.DuplicateNameCheck(Name)){
                JOptionPane.showMessageDialog(rootPane, "Error: The name " + Name + " is already registered.", "Duplicate Name", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            
            // GenerateUniqueID Method -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            UserID = RegisterMethods.GenerateUniqueID();
            // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            
            // User_Encapsulation Object is created here -=-=-=-=-=-=-=-=-=-=-=-
            User_Encapsulation NewUser;
            
            if (UserAdmin.isSelected()) {
                NewUser = new Admin(UserID, Name, Password, UserType, DateRegister);  // Create Admin object
            } else {
                NewUser = new Staff(UserID, Name, Password, UserType, DateRegister);  // Create Staff object
            }
            
            // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            
            // File Writting Area -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
            RegisterMethods.FileWrite(NewUser);
            JOptionPane.showMessageDialog(rootPane, "User successfully registered.", "Wahoo!", JOptionPane.INFORMATION_MESSAGE);
            // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, "Error: File not found, perhaps try to double check the file?");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error: Unable to register user due to Input/Output issue.");
        } finally {
            TxtName.setText("");
            TxtPW.setText("");
            Admin_Staff_Option.clearSelection();
            // I used Try Catch before Lecturer's teaching schedule, so there's that. I got it from:
            // https://www.w3schools.com/java/java_try_catch.asp
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameActionPerformed

    private void TxtPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPWActionPerformed

    private void RegisterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonMouseEntered

    private void RegisterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Admin_Staff_Option;
    private javax.swing.JLabel LabelDisplay_Name;
    private javax.swing.JLabel LabelDisplay_Password;
    private javax.swing.JLabel LabelDisplay_Register;
    private javax.swing.JLabel LabelDisplay_UserType;
    private javax.swing.JPanel Panel_MainFrame;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtPW;
    private javax.swing.JRadioButton UserAdmin;
    private javax.swing.JRadioButton UserStaff;
    // End of variables declaration//GEN-END:variables
}
