/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

// Dylan Denny TP074879

// TO WHOEVER ACCESS MY SOURCE CODE, BY READING THIS YOU AGREE TO NOT STEAL ANY OF MY SOURCE CODE.
// I HAVE GO THROUGH MY WAYS AND STAY UP 4AM JUST TO UNDERSTAND HOW JAVA PROGRAMMING WORKS, PLEASE DON'T QUESTION MY SANITY.
// HONESTLY WHOEVER READS MY CODE ENJOY HAVING BUNCH OF COMMENTS BECAUSE THIS IS HOW I CODE.
// BEST OF LUCK TO ALL MY FRIENDS THIS SEMESTER.
// CODE MAY BE REDUNDANT AND NOT FLEXIBLE FOR OTHER TEAMMATE CODE, HOWEVER MY CODE IS PROBABLY ONLY FLEXIBLE WITHIN MY RANGE.

// For Error Handler -=-=-=-=-=-=-=-=-=-
import java.io.FileNotFoundException;
import java.io.IOException;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// For UI output -=-=-=-=-=-=-=-=-=-=-=-
import javax.swing.JOptionPane;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// For DateRegister -=-=-=-=-=-=-=-=-=-=
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

public class SupplierCreation extends javax.swing.JFrame {

    /**
     * Creates new form SupplierCreation
     */
    public SupplierCreation() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_MainFrame = new javax.swing.JPanel();
        LabelDisplay_Register = new javax.swing.JLabel();
        LabelDisplay_Name = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        TxtName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel_MainFrame.setBackground(new java.awt.Color(51, 51, 51));

        LabelDisplay_Register.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelDisplay_Register.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Register.setText("SUPPLIER CREATION");

        LabelDisplay_Name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDisplay_Name.setForeground(new java.awt.Color(255, 255, 255));
        LabelDisplay_Name.setText("Name :");

        RegisterButton.setBackground(new java.awt.Color(30, 30, 30));
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseExited(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        TxtName.setBackground(new java.awt.Color(30, 30, 30));
        TxtName.setForeground(new java.awt.Color(255, 255, 255));
        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_MainFrameLayout = new javax.swing.GroupLayout(Panel_MainFrame);
        Panel_MainFrame.setLayout(Panel_MainFrameLayout);
        Panel_MainFrameLayout.setHorizontalGroup(
            Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_MainFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelDisplay_Register)
                .addGap(103, 103, 103))
            .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(LabelDisplay_Name)
                .addGap(57, 57, 57)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterButton)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        Panel_MainFrameLayout.setVerticalGroup(
            Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MainFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDisplay_Register)
                .addGap(52, 52, 52)
                .addGroup(Panel_MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDisplay_Name)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(RegisterButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonMouseEntered

    private void RegisterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonMouseExited

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed

        String SupplierName = TxtName.getText();
        String SupplierCode = "";

        DateTimeFormatter DateRegisterFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String DateRegister = LocalDate.now().format(DateRegisterFormat);

        if (SupplierName.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter a supplier name.", "Empty Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // DuplicateNameCheck Method -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            if (SupplierCreationMethod.DuplicateNameCheck(SupplierName)){
                JOptionPane.showMessageDialog(rootPane, "Error: The name " + SupplierName + " is already registered.", "Duplicate Name", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

            // GenerateUniqueID Method -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            SupplierCode = SupplierCreationMethod.GenerateUniqueID();
            // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

            // User_Encapsulation Object is created here -=-=-=-=-=-=-=-=-=-=-=-
            Supplier_Encapsulation NewSupplier = new Supplier_Encapsulation(SupplierCode, SupplierName, DateRegister);
            // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

            // File Writting Area -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
            SupplierCreationMethod.FileWrite(NewSupplier);
            JOptionPane.showMessageDialog(rootPane, "Supplier successfully registered.", "Wahoo!", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            // -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, "Error: File not found, perhaps try to double check the file?");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error: Unable to register user due to Input/Output issue.");
        } finally {
            TxtName.setText("");
            // I used Try Catch before Lecturer's teaching schedule, so there's that. I got it from:
            // https://www.w3schools.com/java/java_try_catch.asp
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierCreation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDisplay_Name;
    private javax.swing.JLabel LabelDisplay_Register;
    private javax.swing.JPanel Panel_MainFrame;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField TxtName;
    // End of variables declaration//GEN-END:variables
}
